version: "3.1"
services:
  api:
    image: postgres:14.2-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USERNAME: postgres
    ports:
      - "5432:5432"
